"""updated foreign key to have name='fk...' , as well as added Snippet model and update User rel with Snippet

Revision ID: 836e007c542f
Revises: 
Create Date: 2023-10-27 19:28:23.530274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836e007c542f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username', type_='unique')

    # ### end Alembic commands ###
